# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iom', '0041_auto_20170213_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='akvoflow',
            name='surveyid',
            field=models.CharField(blank=True, help_text=b'Id van survey', max_length=100, null=True, verbose_name=b'SurveyId'),
        ),
        migrations.AlterField(
            model_name='akvoflow',
            name='monforms',
            field=models.CharField(blank=True, help_text=b'Id van monitoringformulier', max_length=100, null=True, verbose_name=b'Monitoringformulier'),
        ),
        migrations.AlterField(
            model_name='akvoflow',
            name='regform',
            field=models.CharField(blank=True, help_text=b'Id van registratieformulier', max_length=100, null=True, verbose_name=b'Registratieformulier'),
        ),
    ]
